blocknative/react-demo

- package.json
- src/App.js
- src/services.js
- yarn.lock
- Adds MyKey wallet
- Adds MeetOne wallet
- Adds Wallet.io wallet
- Adds Lattice wallet
> Version 0.2.0

- package.json
- yarn.lock
- Updates to the latest versions of Onboard and Notify
> Enhancement: Update Onboard and Notify

- src/services.js
- Removes deprecated wallets
- Changes wallet order
- Adds wallets from newer version of Onboard
> Fix: Update wallets displayed

- package.json
- src/services.js
- yarn.lock
- Updates to the latest version of Onboard.js and Notify.js
- Modifies wallets displayed in wallet select modal
> Version 0.2.1

- package.json
- src/services.js
- yarn.lock
- Updates to the latest Onboard version and adds Liquality wallet.
> 0.2.2-0.1.0: Update Onboard

- package.json
- src/services.js
- yarn.lock
- Updates to the latest Onboard version
- Adds Liquality wallet
> Release 0.3.0

- package.json
> Version 0.5.0

- package.json
- src/services.js
- yarn.lock
- Updates Onboard version to `1.22.0`
- Adds Ownbit wallet
> 0.5.0-0.1.0: [feature] - Ownbit Wallet

- package.json
- yarn.lock
- Updates to the latest Onboard and Notify
> Update client libraries

- package.json
- src/services.js
- yarn.lock
- Updates Notify to the latest release and adds `onerror` handler.
> 0.8.1-0.0.1: [enhancement] - Notify 1.6.2

- package.json
> Release 0.8.2

- package.json
- src/services.js
- yarn.lock
- Updates Onboard to the latest version
- Adds `detectedwallet` module to the wallets array
> 0.8.2-0.1.0: [enhancement] - Detected Wallet

- README.md
- package.json
- src/App.js
- src/services.js
- yarn.lock
- Adds KeepKey wallet
- Adds generic detected injected wallet
> Release 0.9.0

- package.json
- yarn.lock
> Release 0.10.0

- package.json
- src/services.js
- Update onboard v1.34.0
- Moves Keepkey higher up
- Adds Binance Smart Chain wallet
> 0.12.1-0.1.0: Update Onboard v1.34.0

- package.json
- yarn.lock
> 0.12.1-0.1.0: [enhancement] - Notify 1.9.1

- package.json
> Version 0.13.0

- .circleci/config.yml
- package.json
- public/index.html
- src/App.css
- src/App.js
- src/index.js
- src/views/Footer/Footer.css
GAnalytics added and will need testing in staging to confirm env vars are injected properly
Fixed style scoping that was affecting onboard
Fixed styling that was causing console errors
> 0.13.7-0.0.1 : [enhancement] - Add google analytics, fix styling scope

- package.json
- yarn.lock
- Updates Notify.js to the latest to fix replacement transaction notifications
> 0.13.10-0.0.1: [fix] - Update Notify

- package.json
> Release 0.13.11

- package.json
- src/services.js
- yarn.lock
- Updated Onboard version
- Added and tested Tokenary wallet 
- Updated BlankWallet -> BlockWallet according to rebrand
- Testing WalletLink
> 0.13.3 Release - Develop

- package.json
- src/services.js
- yarn.lock
- Updated Onboard version
- Added and tested Tokenary wallet 
- Updated BlankWallet -> BlockWallet according to rebrand
- Testing WalletLink
> 0.13.3 Release - Master

- package.json
- src/App.js
- src/networkEnum.js
- src/services.js
- src/views/Header/Header.js
This release includes web2-onboard implementation!
> 0.14.0 Release  - Develop

- src/services.js
Added gnosis safe wallet that was missed in original deploy and reorder per marketing(Blair)
> Added gnosis safe wallet that was missed in original deploy and reorder per marketing

- package.json
- src/services.js
- yarn.lock
- Updates react package to add the new Account Center UI
- Updates injected-wallets package for Tally wallet support
- Modifies network names to be shorter for account center UI
> 0.16.0-0.1.0: [enhancement] - Account Center

- package.json
> Release 0.17.0

- .circleci/config.yml
- yarn.lock
Return the yarn install --network-concurrency 1 call into build
> 0.19.1 Release - Master 

- package.json
- yarn.lock
- Updates all web3-onboard packages via `yarn upgrade` command.
> Enhancement: Update packages

- package.json
> Release 0.28.1
